### ISSUE TITLE
extensions are wrongly added with `addRelativeDeclarationExtensions` and vue + setup

### ISSUE THREAD

**Issue by pi0** [unjs/mkdist#249] opened 2024-10-01 12:34 UTC
(source: reported by @benjamincanac / reproduced on https://github.com/nuxt/ui/tree/847ee4591abee63cc503bf32d62341d16be6ebc5 `dist/runtimes/types/index.ts` after build)

---

https://github.com/unjs/mkdist/pull/243 introduced a regression in 1.5.7+ with `addRelativeDeclarationExtensions` option since it assumes all source file **will** emit a `.vue.d.ts` companion while files with script setup are not transpiled (and therefore don't emit this file), they need type import with `.vue`

I have added snapshot tests to reproduce it: https://github.com/unjs/mkdist/blob/eb495b042e941c0a68800a0ecb226914a7028218/test/index.test.ts#L177

**Comment by Teages** [comment] 2024-10-08 15:10
seems #251 wouln't fix this issues well because I skip dts generate for js-only `<script>` / `<script setup>` blocks. should I always generate dts for vue files?

(but it will fix the regression here, maybe it is no need to consider the case of pure js `<script>` / `<script setup>` blocks?)

**Comment by danielroe** [comment] 2024-12-18 13:33
resolved in https://github.com/unjs/mkdist/pull/251

**Closed by danielroe** 2024-12-18 13:33 UTC
Labels: bug
